"""
Content OS configuration.

Loads Content OS-specific settings from environment variables.
"""
from pathlib import Path
from universal_video_ai.config import (
    CONTENT_OS_ENABLED,
    CONTENT_OS_MAX_AUTO_REVISIONS,
    CONTENT_OS_MAX_SOURCE_ITEMS,
    CONTENT_OS_ARTIFACT_DIR,
    CONTENT_OS_PROVIDER_TIMEOUT_SECONDS,
    CONTENT_OS_LLM_PROVIDER,
    CONTENT_OS_LLM_MODEL,
    CONTENT_OS_LLM_BASE_URL,
    CONTENT_OS_LLM_API_KEY,
    CONTENT_OS_REQUIRE_RENDER_APPROVAL,
    CONTENT_OS_REQUIRE_PUBLISH_APPROVAL,
)

__all__ = [
    "CONTENT_OS_ENABLED",
    "CONTENT_OS_MAX_AUTO_REVISIONS",
    "CONTENT_OS_MAX_SOURCE_ITEMS",
    "CONTENT_OS_ARTIFACT_DIR",
    "CONTENT_OS_PROVIDER_TIMEOUT_SECONDS",
    "CONTENT_OS_LLM_PROVIDER",
    "CONTENT_OS_LLM_MODEL",
    "CONTENT_OS_LLM_BASE_URL",
    "CONTENT_OS_LLM_API_KEY",
    "CONTENT_OS_REQUIRE_RENDER_APPROVAL",
    "CONTENT_OS_REQUIRE_PUBLISH_APPROVAL",
]

# Ensure artifact directory exists
try:
    CONTENT_OS_ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    pass
